backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "event"
    label: "Event"
    create: true # Allow users to create new documents in this collection
    folder: "_events"
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}"
    identifier_field: title
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "URL", name: "permalink", widget: "string", required: true }
      - { label: "Date", name: "event_date", widget: "date", default: "", format: "DD.MM.YYYY", dateFormat: "DD. MMM. YYYY", required: true }
      - { label: "Image", name: "image", widget: "image", hint: "Seitenverhältnis sollte sein Breite:Höhe 1,5:1, mind. 650x435px" }
      - { label: "Image Alt text", name: "image_alt", widget: "string"}
      - { label: "Lead", name: "lead", widget: "markdown", hint: "Optimales Ergebenis bei ca 2 Absätzen, ca 50 Worte insgesamt" }
      - { label: "CTA", name: "cta", widget: "string" }
      - { label: "CTA URL", name: "cta_url", widget: "string" }
      - { label: "2nd Title", name: "second_title", widget: "string" }
      - { label: "2nd Lead", name: "second_lead", widget: "markdown" }
      - label: "Slider Images"
        label_singular: "Image"
        name: "slider_images"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image"}
          - { label: "Alt text", name: "image_alt", widget: "string"}
      - { label: "Meta: Social Image", name: "meta_image", widget: "image", hint: "Siehe https://de.ryte.com/magazine/open-graph-tags für beste Dimensionen" }
      - { label: "Meta: Social description", name: "meta_description", widget: "markdown", hint: "" }
      - label: "Meta: Layout"
        name: "layout"
        widget: "select"
        default: ["event"]
        options:
          - { label: "Standard Event", value: "event" }
      - label: "Meta: Footer Color"
        name: "meta_footercolor"
        widget: "select"
        default: ["primary"]
        options:
          - { label: "Green", value: "primary" }
          - { label: "White", value: "white" }

  - label: "Pages"
    name: "pages"
    editor:
      preview: true
    files:
      - label: "Home"
        name: "index"
        file: "_data/pages/index.yml"
        fields:
          - { label: "Top Title", name: "top_title", widget: "string" }
          - { label: "Top Subtitle", name: "top_subtitle", widget: "string" }
          - { label: "Top CTA", name: "top_cta", widget: "string" }
          - { label: "Top CTA URL", name: "top_cta_url", widget: "string" }
          - { label: "Featured Image", name: "feature_image", widget: "image" }
          - { label: "Featured Image Alt-text", name: "feature_image_alt", widget: "string" }
          - { label: "Featured Title", name: "feature_title", widget: "string" }
          - { label: "Featured Text", name: "feature_text", widget: "string" }
          - { label: "Featured CTA", name: "feature_cta", widget: "string" }
          - { label: "Featured CTA URL", name: "feature_cta_url", widget: "string" }
          - { label: "Meta: Social Image", name: "meta_image", widget: "image", hint: "Siehe https://de.ryte.com/magazine/open-graph-tags für beste Dimensionen" }
          - { label: "Meta: Social description", name: "meta_description", widget: "markdown", hint: "" }
          - label: "Meta: Footer Color"
            name: "meta_footercolor"
            widget: "select"
            default: ["primary"]
            options:
              - { label: "Green", value: "primary" }
              - { label: "White", value: "white" }
      - label: "Wir"
        name: "wir"
        file: "_data/pages/wir.yml"
        fields:
          - { label: "Top Title", name: "top_title", widget: "string" }
          - { label: "Lead", name: "lead", widget: "markdown" }
          - label: "Slider Images"
            label_singular: "Image"
            name: "slider_images"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image"}
              - { label: "Alt text", name: "image_alt", widget: "string"}
          - { label: "Meta: Social Image", name: "meta_image", widget: "image", hint: "Siehe https://de.ryte.com/magazine/open-graph-tags für beste Dimensionen" }
          - { label: "Meta: Social description", name: "meta_description", widget: "markdown", hint: "" }
          - label: "Meta: Footer Color"
            name: "meta_footercolor"
            widget: "select"
            default: ["primary"]
            options:
              - { label: "Green", value: "primary" }
              - { label: "White", value: "white" }
      - label: "Newsletter"
        name: "newsletter"
        file: "_data/pages/newsletter.yml"
        fields:
          - { label: "Top Title", name: "top_title", widget: "string" }
          - { label: "Lead", name: "lead", widget: "markdown" }
          - { label: "Meta: Social Image", name: "meta_image", widget: "image", hint: "Siehe https://de.ryte.com/magazine/open-graph-tags für beste Dimensionen" }
          - { label: "Meta: Social description", name: "meta_description", widget: "markdown", hint: "" }
          - label: "Meta: Footer Color"
            name: "meta_footercolor"
            widget: "select"
            default: ["primary"]
            options:
              - { label: "Green", value: "primary" }
              - { label: "White", value: "white" }

  - label: "Sitewide Options"
    name: "options"
    editor:
      preview: false
    files:
      - label: "Default Meta Tags"
        name: default_meta_tags
        file: "_data/default_meta_tags.yml"
        fields:
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image" }
      - label: "General Newsletter Options"
        name: newsletter_options
        file: "_data/newsletter_options.yml"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "markdown" }
          - { label: "Background Image", name: "bg_image", widget: "image" }
          - { label: "Subscribe Button Text", name: "subscribe_button_text", widget: "string" }
          - { label: "Subscribe Button URL", name: "subscribe_url", widget: "string" }
      - label: "Top Navigation"
        name: navigation
        file: "_data/top_navigation.yml"
        fields:
          - label: "Left-side Navigation"
            label_singular: "Nav Item"
            name: left_nav
            widget: list
            fields:
              - { label: "Display Text", name: "display_text" , widget: "string", required: true }
              - { label: URL, name: "url", widget: "string", required: true }
          - label: "Right-side Navigation"
            label_singular: "Nav Item"
            name: right_nav
            widget: list
            fields:
              - { label: "Display Text", name: "display_text" , widget: "string", required: true }
              - { label: URL, name: "url", widget: "string", required: true }
